/*
 * IncFile1.h
 *
 * Created: 12/3/2023 11:42:26 AM
 *  Author: KimoStore
 */ 


#ifndef INCFILE1_H_
#define INCFILE1_H_

/*For Pin 1 --> PORTA*/
DDRA = CONCAT(PIN7_DIR,PIN6_DIR,PIN5_DIR,PIN4_DIR,PIN3_DIR,PIN2_DIR,PIN1_DIR,PIN0_DIR);
PORTA= CONCAT(PIN7_PORT,PIN6_PORT,PIN5_PORT,PIN4_PORT,PIN3_PORT,PIN2_PORT,PIN1_PORT,PIN0_PORT);



#endif /* INCFILE1_H_ */